# -*- coding: utf-8 -*-
"""Student1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODrRnYiMwN99oEE96geyYn_Z6lOTxc3p

# 1. Data Gathering

https://www.kaggle.com/datasets/henryshan/student-performance-prediction



#2. Exploratory Data Analysis (EDA)
For a data science project involving the student performance prediction dataset, several basic and essential statistics and insights can be valuable. Here are some key statistics and analyses that you might find useful:

##2.1 Summary Statistics
Use the describe method to get basic summary statistics for numerical features.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

DATAPOR_df = pd.read_csv('Por3.csv')

DATAPOR_df.describe()

"""###2.1.1 Information"""

# Table Information
print(f"The Dataset Is {len(DATAPOR_df)} Rows")
print(f"The Feature {len(DATAPOR_df.columns)} Columns")

# Checking For Any Missing Values
missing_values = DATAPOR_df.isna().sum().sum()
if missing_values == 0:
    print(f"The Dataset has {missing_values} Missing Values")
else:
    print(f"The Dataset has {missing_values} Missing Values")

sns.pairplot(DATAPOR_df,kind='reg',plot_kws={'scatter_kws':{'alpha':0.4},'line_kws':{'color':'orange'}},diag_kws={'color':'green','alpha':.2});

DATAPOR_df.columns

"""## 2.2 Grade Rate"""

G1_rate = DATAPOR_df['G1'].mean()
print(f'Overall G1 Rate: {G1_rate:.2%}')

G2_rate = DATAPOR_df['G2'].mean()
print(f'Overall G2 Rate: {G2_rate:.2%}')

G3_rate = DATAPOR_df['G3'].mean()
print(f'Overall G3 Rate: {G3_rate:.2%}')

"""##2.3 Grade by Gender"""

sex_counts = DATAPOR_df['Sex'].value_counts().sort_index()
print(sex_counts)  # ดูจำนวนผู้ชาย และผู้หญิง 1=ผู้หญิง 2=ผู้ชาย

G1_sex = DATAPOR_df.groupby('Sex')['G1'].mean()
print(G1_sex)

G2_sex = DATAPOR_df.groupby('Sex')['G2'].mean()
print(G2_sex)

G3_sex = DATAPOR_df.groupby('Sex')['G3'].mean()
print(G3_sex)

"""##2.4"""

Age_Dalc = DATAPOR_df.groupby('Age')['Dalc'].mean()
print(Age_Dalc)

Age_Walc = DATAPOR_df.groupby('Age')['Walc'].mean()
print(Age_Walc)

G1_Walc = DATAPOR_df.groupby('Walc')['G1'].mean()
print(G1_Walc)

G2_Walc = DATAPOR_df.groupby('Walc')['G2'].mean()
print(G2_Walc)

G3_Walc = DATAPOR_df.groupby('Walc')['G3'].mean()
print(G3_Walc)

Fedu_Medu = DATAPOR_df.groupby('Fedu')['Medu'].mean()
print(Fedu_Medu)

Fedu_G1 = DATAPOR_df.groupby('Fedu')['G1'].mean()
print(Fedu_G1)

Fedu_G2 = DATAPOR_df.groupby('Fedu')['G2'].mean()
print(Fedu_G2)

Fedu_All_Pass = DATAPOR_df.groupby('Fedu')['All_Pass'].mean()
print(Fedu_All_Pass)

Sex_All_Pass = DATAPOR_df.groupby('Sex')['All_Pass'].mean()
print(Sex_All_Pass)

School_All_Pass = DATAPOR_df.groupby('School')['All_Pass'].mean()
print(School_All_Pass)

"""##2.5 Child falls or pass"""

import pandas as pd
G1_df = 'Por3.csv'  # เปลี่ยนเป็นที่อยู่ของไฟล์ CSV ของคุณ
G1_df = pd.read_csv(G1_df)

# นับจำนวนนักเรียนที่ตก, ผ่าน, และผ่านที่ได้คะแนน 11 และคะแนนเต็ม 20
num_fail = len(G1_df.loc[G1_df['G1'] < 11])
num_pass = len(G1_df.loc[G1_df['G1'] >= 11])

# แสดงผลลัพธ์
print("จำนวนนักเรียนที่ตก:", num_fail)
print("จำนวนนักเรียนที่ผ่าน:", num_pass)

G2_df = 'Por3.csv'  # เปลี่ยนเป็นที่อยู่ของไฟล์ CSV ของคุณ
G2_df = pd.read_csv(G2_df)

# นับจำนวนนักเรียนที่ตก, ผ่าน, และผ่านที่ได้คะแนน 11 และคะแนนเต็ม 20
num_fail = len(G2_df.loc[G2_df['G2'] < 11])
num_pass = len(G2_df.loc[G2_df['G2'] >= 11])

# แสดงผลลัพธ์
print("จำนวนนักเรียนที่ตก:", num_fail)
print("จำนวนนักเรียนที่ผ่าน:", num_pass)

G3_df = 'Por3.csv'  # เปลี่ยนเป็นที่อยู่ของไฟล์ CSV ของคุณ
G3_df = pd.read_csv(G3_df)

# นับจำนวนนักเรียนที่ตก, ผ่าน, และผ่านที่ได้คะแนน 11 และคะแนนเต็ม 20
num_fail = len(G3_df.loc[G3_df['G3'] < 11])
num_pass = len(G3_df.loc[G3_df['G3'] >= 11])

# แสดงผลลัพธ์
print("จำนวนนักเรียนที่ตก:", num_fail)
print("จำนวนนักเรียนที่ผ่าน:", num_pass)

# กำหนดเกณฑ์ในการผ่าน
passing_grade = 11

# คำนวณจำนวนนักเรียนที่ผ่านแต่ละเกรด
pass_G1 = DATAPOR_df[DATAPOR_df['G1'] >= passing_grade].shape[0]
pass_G2 = DATAPOR_df[DATAPOR_df['G2'] >= passing_grade].shape[0]
pass_G3 = DATAPOR_df[DATAPOR_df['G3'] >= passing_grade].shape[0]

# คำนวณสัดส่วนของนักเรียนที่ผ่าน
pass_rate_G1 = pass_G1 / DATAPOR_df.shape[0]
pass_rate_G2 = pass_G2 / DATAPOR_df.shape[0]
pass_rate_G3 = pass_G3 / DATAPOR_df.shape[0]

# แสดงผลลัพธ์
print(f'อัตราการผ่านของเด็ก G1: {pass_rate_G1:.2%}')
print(f'อัตราการผ่านของเด็ก G2: {pass_rate_G2:.2%}')
print(f'อัตราการผ่านของเด็ก G3: {pass_rate_G3:.2%}')

# คำนวณจำนวนนักเรียนที่ไม่ผ่านในแต่ละเกรด
fail_G1 = DATAPOR_df[DATAPOR_df['G1'] < passing_grade].shape[0]
fail_G2 = DATAPOR_df[DATAPOR_df['G2'] < passing_grade].shape[0]
fail_G3 = DATAPOR_df[DATAPOR_df['G3'] < passing_grade].shape[0]

# คำนวณอัตราการตกของแต่ละเกรด
fail_rate_G1 = fail_G1 / DATAPOR_df.shape[0]
fail_rate_G2 = fail_G2 / DATAPOR_df.shape[0]
fail_rate_G3 = fail_G3 / DATAPOR_df.shape[0]

# แสดงผลลัพธ์
print(f'อัตราการตกของเด็ก G1: {fail_rate_G1:.2%}')
print(f'อัตราการตกของเด็ก G2: {fail_rate_G2:.2%}')
print(f'อัตราการตกของเด็ก G3: {fail_rate_G3:.2%}')

# Assuming you have a DataFrame named 'titanic_df' containing the necessary data
# Replace 'Grade1', 'Grade2', 'Grade3', 'School' with the actual column names in your DataFrame

# Filter the data for students who passed in all three grades
passed_students = DATAPOR_df[(DATAPOR_df['G1'] >= passing_grade) &
                              (DATAPOR_df['G2'] >= passing_grade) &
                              (DATAPOR_df['G3'] >= passing_grade)]

# Group by school and calculate the count of students who passed in each school
passing_by_school = passed_students.groupby('School').size()

# Group by school and calculate the total count of students in each school
total_students_by_school = DATAPOR_df.groupby('School').size()

# Calculate the pass rate for each school
pass_rate_by_school = passing_by_school / total_students_by_school

# Display the pass rate for each school
print(pass_rate_by_school)

"""##**2.6** Distribution of information"""

DATAPOR_df['Age'].hist(bins=20, edgecolor='black', alpha=0.7, color='purple')
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Age distribution of students')
plt.show()

print(DATAPOR_df['Sex'].describe())
# Bars
width = 0.35  # the width of the bars
situations = ['Female', 'Male']
data = [1, 2]  # the bar positions on x-axis

plt.bar(data, sex_counts, width, edgecolor='black',
        color=['#FFC0CB', '#0000FF'])
plt.xticks(data, situations)

for p in plt.gca().patches:
    plt.gca().annotate(f'{int(p.get_height())}', (p.get_x() + p.get_width() / 2., p.get_height()),
                       ha='center', va='center', fontsize=10, color='black', xytext=(0, 5), textcoords='offset points')
plt.show()

"""## **2.7** Grade Distribution"""

G1_df['G1'].hist(bins=20, edgecolor='black', alpha=0.7, color='brown')
plt.xlabel('G1')
plt.ylabel('Count')
plt.title('Distribution of Passenger G1')
plt.show()

G2_df['G2'].hist(bins=20, edgecolor='black', alpha=0.7, color='green')
plt.xlabel('G2')
plt.ylabel('Count')
plt.title('Distribution of Passenger G2')
plt.show()

G3_df['G3'].hist(bins=20, edgecolor='black', alpha=0.7, color='red')
plt.xlabel('G3')
plt.ylabel('Count')
plt.title('Distribution of Passenger G3')
plt.show()

"""## 2.8 Correlation Between Features:
Investigate the correlation between numerical features.
"""

correlation_matrix = DATAPOR_df.corr(numeric_only=True)
# Plot the correlation matrix as a heatmap
plt.figure(figsize=(14, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Por Dataset Features')
plt.show()

"""##2.9 School and G1,G2,G3 Analysis

###2.9.1. Embarked and Fare Analysis:

Explore the distribution of fares based on the port of school.
"""

sns.boxplot(x='School', y='G1', data=DATAPOR_df, color='brown')
plt.title('G1 Distribution in each school')
plt.show()

sns.boxplot(x='School', y='G2', data=DATAPOR_df, color='green')
plt.title('G2 Distribution in each school')
plt.show()

sns.boxplot(x='School', y='G3', data=DATAPOR_df, color='red')
plt.title('G3 Distribution in each school')
plt.show()

"""# 3. Feature Engineering"""

import pandas as pd

# Assuming your data is in a DataFrame named 'df'
DATAPOR_df['Pass_G1'] = ((DATAPOR_df['G1']) >= 11).astype(int)  # Sum scores and check if >= 33
DATAPOR_df['Pass_G2'] = ((DATAPOR_df['G2']) >= 11).astype(int)
DATAPOR_df['Pass_G3'] = ((DATAPOR_df['G3']) >= 11).astype(int)
DATAPOR_df['All_Pass'] = ((DATAPOR_df['G1'] + DATAPOR_df['G2'] + DATAPOR_df['G3']) >= 33).astype(int)   # Sum scores and check if >= 33

DATAPOR_df.head()

DATAPOR_df['Things that cause children to fail exams'] = DATAPOR_df['Dalc'] + DATAPOR_df['Walc'] + 1
Effect = DATAPOR_df.groupby('Things that cause children to fail exams')['G1'].mean()
print(Effect)

DATAPOR_df['Things that cause children to fail exams'] = DATAPOR_df['Dalc'] + DATAPOR_df['Walc'] + 1
Effect = DATAPOR_df.groupby('Things that cause children to fail exams')['G2'].mean()
print(Effect)

DATAPOR_df['Things that cause children to fail exams'] = DATAPOR_df['Dalc'] + DATAPOR_df['Walc'] + 1
Effect = DATAPOR_df.groupby('Things that cause children to fail exams')['G1'].mean()
print(Effect)

DATAPOR_df['Things that cause children to fail exams'] = DATAPOR_df['Goout'] + DATAPOR_df['Freetime'] + 1
Effect = DATAPOR_df.groupby('Things that cause children to fail exams')['G1'].mean()
print(Effect)

DATAPOR_df['Things that cause children to fail exams'] = DATAPOR_df['Goout'] + DATAPOR_df['Walc'] + 1
Effect = DATAPOR_df.groupby('Things that cause children to fail exams')['G1'].mean()
print(Effect)

"""# 4. Model Selection, Training and Evaluation

# **Linear Regression:**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select numerical features for linear regression
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Freetime','Higher','Goout', 'Dalc', 'Walc']].copy()
y = DATAPOR_df['G1']

# Handle missing values (e.g., filling mean for simplicity)
X.fillna(X.mean(), inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = linear_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select numerical features for linear regression
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Freetime','Higher','Goout', 'Dalc', 'Walc']].copy()
y = DATAPOR_df['G2']

# Handle missing values (e.g., filling mean for simplicity)
X.fillna(X.mean(), inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = linear_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select numerical features for linear regression
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Freetime','Higher','Goout', 'Dalc', 'Walc']].copy()
y = DATAPOR_df['G3']

# Handle missing values (e.g., filling mean for simplicity)
X.fillna(X.mean(), inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = linear_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

"""#Logistic Regression:"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.impute import SimpleImputer

# เลือก features
DATAPOR_df = pd.read_csv('Por3.csv')
DATAPOR_df['All_Pass'] = ((DATAPOR_df['G1'] + DATAPOR_df['G2'] + DATAPOR_df['G3']) >= 33).astype(int)

X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Freetime','Higher','Goout', 'Dalc', 'Walc','G1','G2','G3']].copy()
y = (DATAPOR_df['All_Pass'])

# แบ่งข้อมูลเป็นชุด training และ testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# สร้างและฝึกโมเดล
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)

# ทำนายบนชุดทดสอบ
y_pred = logistic_model.predict(X_test)

# ประเมินโมเดล
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# คำนวณและพล็อตเมทริกซ์ความสับสน
cm = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{cm}')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.impute import SimpleImputer

#ความแม่นยำของโมเดลอยู่ที่ประมาณ 70 %

# โหลดข้อมูล
DATAPOR_df = pd.read_csv('Por3.csv')

# เลือก features
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Freetime','Higher','Goout', 'Dalc', 'Walc','G1','G2','G3']].copy()
y = (DATAPOR_df['G3'] >= 15).astype(int)

# สร้าง features ใหม่
X['grade_point_average_portuguese'] = X['G1'] + X['G2'] / 2
X['special_skills_score'] = 0
X['interview_score'] = DATAPOR_df['G3'] / 100

# เลือกคุณสมบัติที่จะเป็นตัวทำนาย
features = ['grade_point_average_portuguese', 'special_skills_score', 'interview_score']

# แบ่งข้อมูลออกเป็นชุด training และ testing
X_train, X_test, y_train, y_test = train_test_split(X[features], y, test_size=0.2, random_state=42)

# สร้างและฝึกโมเดล
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)

# ทำนายบนชุดทดสอบ
y_pred = logistic_model.predict(X_test)

# ประเมินโมเดล
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# คำนวณและพล็อตเมทริกซ์ความสับสน
cm = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{cm}')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select features and target variable
# X = titanic_df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Freetime','Higher','Goout', 'Dalc', 'Walc','G1','G2','G3']].copy()
y = (DATAPOR_df['G3'] >= 15).astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the decision tree model
decision_tree_model = DecisionTreeClassifier(random_state=42)
decision_tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = decision_tree_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')

"""#KMeans and Support Vector Machine"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import silhouette_score  # Add this import

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select features and target variable
X = DATAPOR_df[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']]
y = DATAPOR_df['G1']

# Handle missing values
X.loc[:, 'Age'].fillna(X['Age'].mean(), inplace=True)
X.loc[:, 'Dalc'].fillna(X['Dalc'].mode()[0], inplace=True)


# Preprocessing for K-means
kmeans_features = X[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']].copy()
kmeans_features_scaled = StandardScaler().fit_transform(kmeans_features)

# Apply K-meanskmeans
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
X['KMeans_Cluster'] = kmeans.fit_predict(kmeans_features_scaled)

# Preprocessing for SVM
svm_features = X[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']].copy()
svm_features_encoded = pd.get_dummies(X[['Sex', 'Dalc']], drop_first=True)
X_svm = pd.concat([svm_features, svm_features_encoded], axis=1)

# Split the data into training and testing sets
X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(X_svm, y, test_size=0.2, random_state=42)

# Apply SVM
svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', SVC(random_state=42))
])

svm_model.fit(X_train_svm, y_train_svm)
svm_accuracy = svm_model.score(X_test_svm, y_test_svm)

pd.options.mode.chained_assignment = None  # ยกเลิกการแสดงเตือน SettingWithCopyWarning

print(f'K-means Clustering - Silhouette Score: {silhouette_score(kmeans_features_scaled, X["KMeans_Cluster"])}')
print(f'SVM Accuracy: {svm_accuracy}')

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import silhouette_score  # Add this import

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select features and target variable
X = DATAPOR_df[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']]
y = DATAPOR_df['G2']

# Handle missing values
X.loc[:, 'Age'].fillna(X['Age'].mean(), inplace=True)
X.loc[:, 'Dalc'].fillna(X['Dalc'].mode()[0], inplace=True)


# Preprocessing for K-means
kmeans_features = X[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']].copy()
kmeans_features_scaled = StandardScaler().fit_transform(kmeans_features)

# Apply K-meanskmeans
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
X['KMeans_Cluster'] = kmeans.fit_predict(kmeans_features_scaled)

# Preprocessing for SVM
svm_features = X[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']].copy()
svm_features_encoded = pd.get_dummies(X[['Sex', 'Dalc']], drop_first=True)
X_svm = pd.concat([svm_features, svm_features_encoded], axis=1)

# Split the data into training and testing sets
X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(X_svm, y, test_size=0.2, random_state=42)

# Apply SVM
svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', SVC(random_state=42))
])

svm_model.fit(X_train_svm, y_train_svm)
svm_accuracy = svm_model.score(X_test_svm, y_test_svm)

pd.options.mode.chained_assignment = None  # ยกเลิกการแสดงเตือน SettingWithCopyWarning

print(f'K-means Clustering - Silhouette Score: {silhouette_score(kmeans_features_scaled, X["KMeans_Cluster"])}')
print(f'SVM Accuracy: {svm_accuracy}')

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import silhouette_score  # Add this import

# Load Titanic dataset (replace 'path/to/titanic/train.csv' with your dataset path)
DATAPOR_df = pd.read_csv('Por3.csv')

# Select features and target variable
X = DATAPOR_df[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']]
y = DATAPOR_df['G3']

# Handle missing values
X.loc[:, 'Age'].fillna(X['Age'].mean(), inplace=True)
X.loc[:, 'Dalc'].fillna(X['Dalc'].mode()[0], inplace=True)


# Preprocessing for K-means
kmeans_features = X[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']].copy()
kmeans_features_scaled = StandardScaler().fit_transform(kmeans_features)

# Apply K-meanskmeans
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
X['KMeans_Cluster'] = kmeans.fit_predict(kmeans_features_scaled)

# Preprocessing for SVM
svm_features = X[['Sex','Age','Pstatus','Medu','Fedu', 'Mjob','Fjob','Studytime','Schoolsup','Famsup','Paid','Higher','Freetime','Goout','Dalc','Walc','G1','G2','G3']].copy()
svm_features_encoded = pd.get_dummies(X[['Sex', 'Dalc']], drop_first=True)
X_svm = pd.concat([svm_features, svm_features_encoded], axis=1)

# Split the data into training and testing sets
X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(X_svm, y, test_size=0.2, random_state=42)

# Apply SVM
svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', SVC(random_state=42))
])

svm_model.fit(X_train_svm, y_train_svm)
svm_accuracy = svm_model.score(X_test_svm, y_test_svm)

pd.options.mode.chained_assignment = None  # ยกเลิกการแสดงเตือน SettingWithCopyWarning

print(f'K-means Clustering - Silhouette Score: {silhouette_score(kmeans_features_scaled, X["KMeans_Cluster"])}')
print(f'SVM Accuracy: {svm_accuracy}')

import plotly.express as px
import matplotlib

# Interactive Scatter Plot
fig = px.scatter(DATAPOR_df, x='Age', y='G1', color='Medu')
fig.show()

import plotly.express as px
import matplotlib

# Interactive Scatter Plot
fig = px.scatter(DATAPOR_df, x='Age', y='G1', color='Fedu')
fig.show()

import matplotlib.pyplot as plt

# นำเข้าข้อมูล
DATAPOR_df = pd.read_csv("Por3.csv")

# เตรียมข้อมูลสำหรับกราฟ
for grade in ["G1", "G2", "G3"]:
    DATAPOR_df[grade] = DATAPOR_df.groupby("Medu")[grade].mean()

# สร้างกราฟ
fig, ax = plt.subplots(3,1, figsize=(10,5))
fig.subplots_adjust(hspace=0.5)
for grade, ax in zip(["G1", "G2", "G3"], ax):
    ax.plot(DATAPOR_df[grade].index, DATAPOR_df[grade])
    ax.set_title(grade)

# แสดงกราฟ
plt.show()

import matplotlib.pyplot as plt

# นำเข้าข้อมูล
DATAPOR_df = pd.read_csv("Por3.csv")

# เตรียมข้อมูลสำหรับกราฟ
for grade in ["G1", "G2", "G3"]:
   DATAPOR_df[grade] = DATAPOR_df.groupby("Fedu")[grade].mean()

# สร้างกราฟ
fig, ax = plt.subplots(3,1, figsize=(10,5))
fig.subplots_adjust(hspace=0.5)
for grade, ax in zip(["G1", "G2", "G3"], ax):
    ax.plot(DATAPOR_df[grade].index, DATAPOR_df[grade])
    ax.set_title(grade)

# แสดงกราฟ
plt.show()

# Define the number of columns for the grid layout
num_columns = 3  # You can change this to any number of columns you prefer

# Calculate the number of rows required based on the number of columns
num_features = DATAPOR_df.shape[1]
num_rows = (num_features + num_columns - 1) // num_columns

# Create the subplots with the desired number of columns
fig, axes = plt.subplots(num_rows, num_columns, figsize=(15, 3 * num_rows))

# Loop through each feature and create histograms
for i, ax in enumerate(axes.ravel()):
    if i < num_features:
        sns.histplot(DATAPOR_df[DATAPOR_df.columns[i]], bins=20, kde=True, ax=ax)
        ax.set_title(f'{DATAPOR_df.columns[i]}')

# Adjust layout and display the plot
plt.tight_layout()
plt.show()

"""#XGboost with the student dataset



"""

pip install pandas numpy xgboost scikit-learn

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
import xgboost as xgb

# Data preprocessing
# For simplicity, we drop some features and handle missing values
#DATAPOR_df = DATAPOR_df.drop(['School','Pstatus','Mjob','Fjob','Reason', 'Schoolsup','Famsup'], axis=1)


# Convert categorical variables to dummy/indicator variables
#DATAPOR_df = pd.get_dummies(DATAPOR_df, columns=[ 'Sex','Dalc'], drop_first=True)
DATAPOR_df = pd.read_csv('Por3.csv')
DATAPOR_df['Pass_G1'] = ((DATAPOR_df['G1']) >= 11).astype(int)

# Split the data into features (X) and target variable (y)
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Famsup','Freetime','Higher','Goout', 'Dalc', 'Walc']]
y = (DATAPOR_df['Pass_G1'])


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the XGBoost model
model = XGBClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Feature importance plot (if you want to visualize feature importance)
import matplotlib.pyplot as plt
from xgboost import plot_importance

plt.figure(figsize=(10, 6))
plot_importance(model)
plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
import xgboost as xgb

# Data preprocessing
# For simplicity, we drop some features and handle missing values
#DATAPOR_df = DATAPOR_df.drop(['School','Pstatus','Mjob','Fjob','Reason', 'Schoolsup','Famsup'], axis=1)


# Convert categorical variables to dummy/indicator variables
#DATAPOR_df = pd.get_dummies(DATAPOR_df, columns=[ 'Sex','Dalc'], drop_first=True)
DATAPOR_df = pd.read_csv('Por3.csv')
DATAPOR_df['All_Pass'] = ((DATAPOR_df['G1'] + DATAPOR_df['G2'] + DATAPOR_df['G3']) >= 33).astype(int)

# Split the data into features (X) and target variable (y)
X = DATAPOR_df[['Pstatus','Medu','Fedu','Mjob','Fjob','Studytime','Activities','Famsup','Freetime','Higher','Goout', 'Dalc', 'Walc','Paid']]
y = (DATAPOR_df['All_Pass'])


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the XGBoost model
model = XGBClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Feature importance plot (if you want to visualize feature importance)
import matplotlib.pyplot as plt
from xgboost import plot_importance

plt.figure(figsize=(10, 6))
plot_importance(model)
plt.show()

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')


# Compute and plot the confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Not pass', 'Pass'],
            yticklabels=['Not pass', 'Pass'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()